version: '3.1'
services:
  lunch_web_rest:
    image: lunch_web_rest
    build: .
    ports:
      - "8080:8080"
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
      - MONGO_INITDB_DATABASE=lunch_web
    volumes:
      - ./mongo_data:/data/db
