# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install poetry
      
      - name: Install package
        run: |
          poetry install

      - name: Run test suite
        run: |
          poetry run pytest tests/